version: "3.8"

services:
    synapse:
        image: matrixdotorg/synapse:latest
        container_name: matrix-synapse
        restart: unless-stopped
        environment:
            - SYNAPSE_SERVER_NAME=matrix.linehost.pro
            - SYNAPSE_REPORT_STATS=no
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_DB=synapse
            - POSTGRES_USER=synapse
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        volumes:
            - synapse_data:/data
            - ./homeserver.yaml:/data/homeserver.yaml:ro
            - ./matrix.linehost.pro.log.config:/data/matrix.linehost.pro.log.config:ro
        depends_on:
            - postgres
            - redis
        ports:
            - "8008:8008"
        networks:
            - matrix-net

    postgres:
        image: postgres:15-alpine
        container_name: matrix-postgres
        restart: unless-stopped
        environment:
            - POSTGRES_DB=synapse
            - POSTGRES_USER=synapse
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - matrix-net

    redis:
        image: redis:7-alpine
        container_name: matrix-redis
        restart: unless-stopped
        command: redis-server --appendonly yes
        volumes:
            - redis_data:/data
        networks:
            - matrix-net

    # Element Web Client (opcional)
    element:
        image: vectorim/element-web:latest
        container_name: matrix-element
        restart: unless-stopped
        volumes:
            - ./element-config.json:/app/config.json:ro
        ports:
            - "8080:80"
        networks:
            - matrix-net

volumes:
    synapse_data:
    postgres_data:
    redis_data:

networks:
    matrix-net:
        driver: bridge
